a_tensor_initialization

In [1]:
import torch

In [2]:
t1 = torch.Tensor([1,2,3], device='cpu')
print(t1.dtype)     # >>> torch.float32 # >>> Tensor는 float32임
print(t1.device)    # >>> cpu
print(t1.requires_grad) # >>> Fasle  해당 텐서에 대한 연산 과정을 추적하고, 자동으로 미분을 계산할지 여부를 결정하는 속성이다. 기본값은 False이다.requires_grad=True인 텐서는 이후 계산을 그래프로 기록해서 backward()를 호출했을때 자동을 미분 결과를 구해준다.
print(t1.size())    # torch.Size([3])
print(t1.shape)     # torch.Size([3])

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda() #텐서를 gpu메모리로 옮김
t1_cpu = t1.cpu()   # 텐서를 cpu메모리로 옮기는 함수


torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
# torch.tensor function
t2 = torch.tensor([1,2,3], device='cpu')
print(t2.dtype) # >>> torch.int64 # >>> tensor는 int64임
print(t2.device) # >>> cpu
print(t2.requires_grad) # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()


torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
import torch

a1 = torch.tensor(1)            #shape:torch.Size([]), ndims(=rank):0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])          #shape: torch.Size([1]), ndims(=rank):1
print(a2.shape, a2.ndim)

a3 = torch. tensor([1,2,3,4,5]) #shape: torch.Size([5]), ndims(=rank):1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1],[2],[3],[4],[5]])    #shape: torch.Size([5,1]), ndims(=rank) :2

a5 = torch.tensor([             #shape: torch.Size([3,2]), ndims(=rank):2
    [1,2],
    [3,4],
    [5,6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([             #shape: torch.Size([3,1,2,1]),ndims(=rank):3
    [[1],[2]],
    [[3],[4]],
    [[5],[6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([             #shape: torch.Size([3,1,2,1)], ndims(=rank): 4
    [[[1],[2]]],
    [[[3],[4]]],
    [[[5],[6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([             #shape: torch.Size([3,1,2,3]), ndims(=rank):4
    [[[1,2,3],[2,3,4]]],
    [[[3,1,1],[4,4,5]]],
    [[[5,6,2],[6,3,1]]]
])
print(a8.shape, a8.ndim)

a9 = torch.tensor([             #shape: torch.Size([3,1,2,3,1]), ndims(=rank) : 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([            #shape: torch.Size([4,5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([            #shape: torch.Size([4,1,5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([            #ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],      #에러 이유: PyTorch에서 torch.tensor로 텐서를 생성할때는 모든 차원(dim)의 길이가 같아야 하는데 길이가 3,2이기 때문에 에러가 난다.
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

b_tensor_initialization_copy

In [5]:
import torch

l1 = [1,2,3]
t1 = torch.Tensor(l1)           #클래스 생성자, float32, 복사

l2 = [1,2,3]
t2 = torch.tensor(l2)           #팩토리 함수, dtype 자동 추론(int64), 복사

l3 = [1,2,3]
t3 = torch.as_tensor(l3)        # tensor는 원본을 복사해서 새 텐서를 만들지만 as_tensor는 원본과 연결되어 복사를 최소화 한다. tensor는 원본의 값이 변경되어도 영향을 받지 않지만, as_tensor는 원본이 변경되면 같이 변경되어 예기치 않은 버그를 일으킬수있다.하지만 여기서 l3는 파이썬 리스트이므로 원본과 공유되지 않는다. numpy를 사용해 np.array로 만든 배열인 경우에만 공유가 된다.

l1[0] = 100                     # 원본 리스트 변경
l2[0] = 100                     # 원본 리스트 변경
l3[0] = 100                     # 원본 리스트 변경

print(t1)                       # Tensor는 float32이기 때문에 tensor([1,2,3])이 아닌 tensor([1., 2., 3.])처럼 부동소수점으로 출력된다.
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [6]:
import torch
import numpy as np

l4 = np.array([1,2,3])
t4 = torch.Tensor(l4)

l5 =np.array([1,2,3])
t5 = torch.tensor(l5)

l6 = np.array([1,2,3])
t6 = torch.as_tensor(l6)        #np.array이므로 원본이 변경되면 텐서도 같이 변경

l4[0] = 100                     # 원본 리스트 변경
l5[0] = 100                     # 원본 리스트 변경
l6[0] = 100                     # 원본 리스트 변경

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


c_tensor_initialization_constant_values

In [7]:
import torch
                                #*_like(tensor) -> 주어진 텐서와 같은 shape과 dtype으로 새 텐서를 생성
                                # (n,)
                                # 파이썬 에서는 길이가 1인 튜플
                                # PyTorch에서 size 인자는 텐서의 shape을 나타내는 튜플이어야 한다.
                                # 그래서 길이가 n인 1차원 텐서이다.
t1 = torch.ones(size=(5,))      # or torch.ones(5)
                                # 길이 5짜리 1차원 텐서를 모두 1로 채움
t1_like = torch.ones_like(input=t1)
print(t1)                       # >>> tensor([1.,1.,1.,1.,1.])
print(t1_like)                  # >>> tensor([1.,1.,1.,1.,1.])

t2 = torch.zeros(size=(6,))     # or torch.zeros(6)
                                # 길이 6짜리 1차원 텐서를 모두 0으로 채움
t2_like = torch.zeros_like(input=t2)
print(t2)                       # >>> tensor([0.,0.,0.,0.,0.,0.])
print(t2_like)                  # >>> tensor([0.,0.,0.,0.,0.,0.])

t3 = torch.empty(size=(4,))     # or torch.zeros(4)
                                # 초기화를 하지 않고 길이 4짜리 1차원 텐서를 모두 비어있는 값으로 채움
                                # 실행환경에 따라서 쓰레기 값이 나올수있음
t3_like = torch.empty_like(input=t3)
print(t3)                       # >>> tensor([0.,0.,0.,0.])
print(t3_like)                  # >>> tensor([0.,0.,0.,0.])

t4 = torch. eye(n=3)            # eye(n) -> nxn 단위행렬 생성
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([1., 2., 3., 0.])
tensor([-3.0769e-05,  1.0258e-42,  0.0000e+00,  0.0000e+00])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


d_tensor_initialization_random_values

In [8]:
import torch

t1 = torch.randint(low=10, high=20, size=(1,2))     # shape이 [1,2] 인 텐서를 10이상 20미만의 정수 랜덤값 생성하여 채움
print(t1)

t2 = torch.rand(size=(1,3))                         # shape이 [1,3]인 텐서를 [0,1) 구간에서 균등 분포를 따르는 난수로 채움
print(t2)

t3 = torch.randn(size=(1,3))                        # shape이 [1,3]인 텐서를 평균이 0이고 표준편차가 1인 정규분포 난수로 채움
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3,2))   # shape이 [3,2]인 텐서를 평균 10.0, 표준편차 1.0인 정규분포에서 난수 생성후 채움
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)    # [0.0, 5.0] 구간을 3등분해서 출력
print(t5)

t6 = torch.arange(5)                                # 0부터 5미만까지 1씩 증가
print(t6)

tensor([[19, 15]])
tensor([[0.0578, 0.3304, 0.5857]])
tensor([[0.4727, 0.3563, 0.7999]])
tensor([[ 8.6892, 10.5474],
        [ 7.6586, 11.3469],
        [ 8.4642,  9.9671]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


In [9]:
import torch
# seed를 고정하면 난수가 재현 가능해진다.
# random1, random2는 서로 다른 난수지만, 항상 같은 시드라면 실행할 때마다
# 동일한 값이 나온다.
torch.manual_seed(1729)
random1 = torch.rand(2,3)
print(random1)

random2 = torch.rand(2,3)
print(random2)

print()

# 시드를 다시 1729로 고정했으므로
# random3 == random1
# random4 == random2이다.

torch.manual_seed(1729)
random3 = torch.rand(2,3)
print(random3)

random4 = torch.rand(2,3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


e_tensor_type_conversion

In [10]:
import torch

a = torch.ones((2,3))               # 2*3 크기의 텐서를 1로 초기화
print(a.dtype)                      # >>> tortch

b = torch.ones((2,3), dtype=torch.int16)    # 정수형 16비트 텐서 생성
print(b)

c = torch.rand((2,3), dtype=torch.float64)*20.  # torch.rand [0,1) 구간 균등분포 랜덤값
                                                # 실수형 64비트 텐서 생성
                                                # *20. -> 값의 범위를 0~20 으로 스케일링
print(c)

d = b.to(torch.int32)                           # dtype int16에서 int32로 변환
print(d)

double_d = torch.zeros(10,2).double()
short_e = torch.tensor([[1,2]],dtype=torch.short)

double_d = torch.zeros(10,2).double()
short_e = torch.ones(10,2).short()

double_d =torch.zeros(10,2).type(torch.double)
short_e = torch.ones(10,2).to(dtype=torch.short)

double_d = torch.zeros(10,2).type(torch.double)
short_e = torch.ones(10,2).type(dtype=torch.short)

# 위의 방법 모두 dytpe 형변환 방법임 결과는 같음

print(double_d.dtype)
print(short_e.dtype)

# PyTorch는 연산시 더 정밀한 dtype으로 자동 승격
double_f = torch.rand(5, dtype=torch.double) # dtype == float64
short_g = double_f.to(torch.short)           # dtype == int 16
print((double_f * short_g).dtype)           # >>> torch.float64


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


f_tensor_operations

In [11]:
import torch

t1 = torch.ones(size=(2,3))
t2 = torch.ones(size=(2,3))
t3 = torch.add(t1,t2)           # t1 + t2와 동일
t4 = t1 + t2                    # 연산자 오버로딩 사용
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [12]:
t5 = torch.sub(t1,t2)           # t1 - t2와 동일
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
t7 = torch.mul(t1,t2)           # t1 * t2와 동일
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
t9 = torch.div(t1,t2)           # t1 / t2와 동일
t10 = t1/t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


g_tensor_operations_mm

In [15]:
import torch

t1 = torch.dot(             # torch.dot은 1차원 벡터 두개의 내적을 계산
    torch.tensor([2,3]), torch.tensor([2,1])
)                           # 결과 : tensor(7)로 스칼라 값임
print(t1,t1.size())         # 스칼라값이므로 0차원 텐서임

t2 = torch.randn(2,3)       # (2x3) 행렬
t3 = torch.randn(3,2)       # (3x2) 행렬
t4 = torch.mm(t2,t3)        # torch.mm은 2차언 행렬 곱셉을 의미
                            # 결과 (2x2) 행렬
print(t4,t4.size())

t5 = torch.randn(10,3,4)    # (batch=10, 3x4 행렬)
t6 = torch.randn(10,4,5)    # (batch=10, 4x5 행렬)
t7 = torch.bmm(t5,t6)       # (batch=10, 3x5 행렬 결과)
                            # batch란 데이터를 한번에 묶어서 처리하는 단위
                            # ex) 1000개의 셈플, batch size=100이면 10번의 반복이 필요
                            # 이러한 과정을 한 epoch라고 함
print(t7.size())

tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


h_tensor_operations_matmul

In [16]:
import torch

# vector x vector : dot product
t1 = torch.randn(3)                 # shape(3,)
t2 = torch.randn(3)                 # shape(3,)
print(torch.matmul(t1,t2).size())   # torch.Size([])
                                    # 1차원 벡터끼리 곱하면 스칼라값이 나와 차원이 0이다.

# matrix x vector: broadcaste dot
t3 = torch.randn(3,4)               # shape(3,4)
t4 = torch.randn(4)                 # shape(4,)
print(torch.matmul(t3,t4).size())   # torch.Size([3])
                                    # (3x4)행렬 x (4,)행렬 결과는 (3,)벡터이다.

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10,3,4)            # (batch=10, 3x4 행렬들)
t6 = torch.randn(4)                 # (4,) 벡터
print(torch.matmul(t5,t6).size())   # torch.Size([10,3])
                                    # (3x4)행렬 x (4,) 행렬 결과는 (3,)
                                    # 이걸 10개 batch에 대해 반복하므로
                                    # 결과 shape = (10,3)

# bathed matrix x batched matrix: bmm
t7 = torch.randn(10,3,4)            # (batch=10, 3x4 행렬들)
t8 = torch.randn(10,4,5)            # (batch=10, 4x5 행렬들)
print(torch.matmul(t7,t8).size())   # torch.Size([10,3,5])

# batched matrix x matrix: bmm
t9 = torch.randn(10,3,4)            # (batch=10, 3x4 행렬들)
t10 = torch.randn(4,5)              # (4x5) 행렬
print(torch.matmul(t9,t10).size())  # torch.Size([10,3,5])


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


i_tensor_broadcasting

In [17]:
import torch

t1 = torch.tensor([1.0,2.0,3.0])
t2 = 2.0
print(t1*t2)
# element-wise 연산으로 스칼라 2.0이 벡터 t1의 모든 원소에 곱해진다.

tensor([2., 4., 6.])


In [18]:
import torch

t3 = torch.tensor([[0,1],[2,4],[10,10]])
t4 = torch.tensor([4,5])
print(t3-t4)
# t3는 (3x2), t4는 (2,) -> PyTorch가 마지막 차원을 맞춰서 브로드 캐스팅
# 각 행을 [4,5] 뺀다.

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [19]:
import torch

t5 = torch.tensor([[1.,2.],[3.,4.]])
print(t5 + 2.0)     #t5.add(2.0)
print(t5 - 2.0)     #t5.sub(2.0)
print(t5 * 2.0)     #t5.mul(2.0)
print(t5 / 2.0)     #t5.div(2.0)
# 스칼라 연산도 자동 브로드캐스팅된다. 따라서 모든 원소에 적용된다.

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [20]:
import torch

def normalize(x):
    return x/255

t6 = torch.randn(3,28,28)
print(normalize(t6).size())
# 픽셀값(0~255)을  0~1 범위로 맞추는 전처리 예제이다. shape 변화는 없다.

torch.Size([3, 28, 28])


In [21]:
import torch

t7 = torch.tensor([[1,2],[0,3]])    # torch.Size([2,2])
t8 = torch.tensor([[3,1]])          # torch.Size([1,2])
t9 = torch.tensor([[5],[2]])        # torch.Size([2,1])
t10 = torch.tensor([7])             # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[8, 9], [7, 10]])

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [22]:
import torch

t11 = torch.ones(4,3,2)
t12 = t11 * torch.rand(3,2)     # 3rd & 2nd dims identical to t11, dim 0 absent
                                # (3,2)가 브로드캐스트 -> 결과 (4,3,2)
print(t12.shape)

t13 = torch.ones(4,3,2)
t14 = t13 * torch.rand(3,1)     # 3rd dim = 1, 2nd dim is identical to t13
                                # (3,1) -> (3,2)로 브로드캐스트 -> 결과 (4,3,2)
print(t14.shape)

t15 = torch.ones(4,3,2)
t16 = t15 * torch.rand(1,2)     # 3rd dim is identical to t15, 2nd dim is 1
                                # (1,2) -> (3,2)로 브로캐스트 -> 결과 (4,3,2)
print(t16.shape)

t17 = torch.ones(5,3,4,1)
t18 = torch.rand(3,1,1)         # 2nd dim is identical to t17, 3rd and 4th dims are 1
                                # (3,1,1) -> (3,4,1)로 브로드캐스트 -> 결과 (5,3,4,1)
print((t17 + t18).size())



torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [23]:
import torch

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])
# 모든 경우에서 브로캐스팅 규칙에 따라 shape이 확장된다.

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1
# 브로드캐스팅은 뒤에서부터 차원을 비교한다. 만약 크기가 서로 다르고, 둘다 1이 아닌 경우 RuntimeError 발생

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


In [24]:
import torch

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([5,5,5,5])
# element-wise연산으로 스칼라 곱을 하면된다
t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([25,25,25,25])
# elsement-wise연산으로 각원소를 2의 거듭제곱을 한다.
exp = torch.arange(1., 5.)  # tensor([1.,2.,3.,4.])
a = torch.arange(1., 5.)  # tensor([1.,2.,3.,4.])
t29 = torch.pow(a, exp)     # element-wise연산으로 각 원소끼리 거듭제곱 한다.
print(t29)  # >>> tensor([1.,4.,27.,256.])



tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


j_tensor_indexing_slicing

In [25]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])  # 1행 출력
print(x[:, 1])  # >>> tensor([1, 6, 11])    # 모든행에서 1번째 열만 뽑기
print(x[1, 2])  # >>> tensor(7)             # 1행 2열 원소
print(x[:, -1])  # >>> tensor([4, 9, 14)    # 모든행에서 마지막 열 뽑기


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [26]:
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])        # 1행부터 끝까지 슬라이싱
print(x[1:, 3:])    # >>> tensor([[ 8,  9], [13, 14]])
                    # 1행부터 끝까지, 그리고 3열 부터 끝까지 슬라이싱

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [27]:
y = torch.zeros((6, 6))     #6x6 영행렬 생성
y[1:4, 2] = 1               # 1~3행, 2열에 1 대입
print(y)

print(y[1:4, 1:4])          # 위에서 수정된 부분만 잘라낸 3x3 서브 매트릭스


tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [28]:
z = torch.tensor(       # z.shape = (3,4)
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])            # 앞에서 2행만 슬라이싱
print(z[1:, 1:3])       # 1행부터 끝까지, 1~2열 슬라이싱
print(z[:, 1:])         # 모든행, 1열부터 끝까지 슬라이싱

z[1:, 1:3] = 0          # 1행부터 끝까지, 1열부터 2열 구간을 0으로 변경
print(z)


tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


k_tensor_reshaping

In [29]:
import torch

t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = t1.view(3,2)   #shape becomes (3,2)
                    # view: 메모리 연속성을 유지한채로 모양만 바꿈 (조건 맞지 않으면 오류 가능)
t3 = t1.reshape(1,6)    #shape becomes (1,6)
                        # reshape: 내부적으로 필욯면 데이터를 복사해서라도 모양을 맞춤
print(t2)
print(t3)

# torch.arange() 는 일정한 간격으로 숫작가 증가하는 1차원 텐서를 만드는 함수
t4 = torch.arange(8).view(2,4)  #shape becomes (2,4)
                                # 8개의 원소를 2행 4열로 배치
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
                                    # 8개의 원소를 2행 3열로 배치
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [30]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1 # 크기가 1인 모든 차원 삭제
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0    #지정한 dim이 0인 차원 삭제
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [31]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1 # 해당위치에 새로운 차원 (크기=1)을 추가함
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [32]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)   # 모든 차원을 하나로 펼친다.

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)   # 특정 차원(1)부터 펼친다.

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [33]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])        #premute(dims) : 원하는 순서대로 차원 재배치

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)    # Shape becomes (3, 2)
                                    # transpose(dim0,dim1): 두 차원의 위치를 맞바꿈
print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)
                    # 2차원 행렬의 전치 단축함수
print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


l_tensor_concat

In [34]:
import torch

t1 = torch.zeros([2,1,3])
t2 = torch.zeros([2,3,3])
t3 = torch.zeros([2,2,3])

t4 = torch.cat([t1,t2,t3], dim=1)   # dim=1 을 합친다.
print(t4.shape) #세 텐서 모두 (2,*,3) 모양이라 두 번째 축만 늘어난다.

torch.Size([2, 6, 3])


In [35]:
t5 = torch.arange(0,3)  # tensor([0,1,2])
t6 = torch.arange(3,8)  # tensor([3,4,5,6,7])

t7 = torch.cat((t5,t6), dim=0) # 벡터 연결은 단순히 이어붙이는 것이다.
print(t7.shape)     #>>> torch.Size([8])
print(t7)       # >>> tensor([0,1,2,3,4,5,6,7])


torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [36]:
t8 = torch.arange(0,6).reshape(2,3)     #torch.Size([2,3])
t9 = torch.arange(6,12).reshape(2,3)    #torch.Size([2,3])

# 2차원 텐서간 병합
t10 = torch.cat((t8,t9), dim=0 )    # (2,3) + (2,3) -> (4,3)
print(t10.size())   # >>> torch.Size([4,3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8,t9), dim=1)     # (2,3) + (2,3) -> (2,6)
print(t11.size())   # >>> torch.Size([2,6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [37]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12,t13,t14), dim=0)   # (2,3) + (2,3) + (2,3) -> (6,3)
print(t15.size())   #>>> torch.Size([6,3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12,t13,t14), dim=1)   # (2,3) + (2,3) + (2,3) -> (2,9)
print(t16.size())   # >>> torch.Size([2,9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [38]:
# 3차원 텐서
t17 = torch.arange(0,6).reshape(1,2,3) #torch.Size([1,2,3])
t18 = torch.arange(6,12).reshape(1,2,3) # torch.Size([1,2,3])

t19 = torch.cat((t17,t18), dim=0)   # (1,2,3) + (1,2,3) -> (2,2,3)
print(t19.size())   # >>> torch.Size([2,2,3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17,t18), dim=1)   # (1,2,3) + (1,2,3) -> (1,4,3)
print(t20.size())   # >>> torch.Size([1,4,3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17,t18), dim=2)   # (1,2,3) + (1,2,3) -> (1,2,6)
print(t21.size())   # >>> torch.Size([1,2,6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


m_tensor_stacking

In [39]:
import torch

# torch.cat(tensor, dim)
# 이미 존재하는 차원을 기준으로 이어붙임
# 따라서 보통 unsqueeze로 차원을 맞춰줘야 원하는 모양이 나온다.

# torch.stack(tensors,dim)
# 새로운 차원을 하나 추가한 뒤, 그 차원에서 쌓음
# unsqueeze를 따로 안 써도 된다.

t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[7,8,9],[10,11,12]])

t3 = torch.stack([t1,t2],dim=0) # stach은 자동으로 차원 추가
t4 = torch.cat([t1.unsqueeze(dim=0),t2.unsqueeze(dim=0)],dim=0) #cat은 unsqeueze로 직접 차원을 맞춘 후 이어 붙임
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1,t2],dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1),t2.unsqueeze(dim=1)],dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1,t2],dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2),t2.unsqueeze(dim=2)],dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [40]:
t9 = torch.arange(0,3)  # tensor([0,1,2])
t10 = torch.arange(3,6) # tensor([3,4,5])

print(t9.size(),t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9,t10),dim=0)
print(t11.size())   # >>>torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0),t10.unsqueeze(0)),dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9,t10),dim=1)
print(t13.size())   # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])

t14 = torch.cat((t9.unsqueeze(1),t10.unsqueeze(1)),dim=1)
print(t13.equal(t14))
# >>> True

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


n_tensor_vstack_htack

In [41]:
import torch

t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = torch.vstack((t1,t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1],[2],[3]])
t5 = torch.tensor([[4],[5],[6]])
t6 = torch.vstack((t4,t5))          #1차원 텐서를 행방향으로 쌓는다
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(t7.shape)
# >>> (2,2,3)

t8 = torch.tensor([
    [[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24]]
])
print(t8.shape)
# >>> (2,2,3)

t9 = torch.vstack([t7,t8])
print(t9.shape)
# >>> (4,2,3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [42]:
t10 = torch.tensor([1,2,3])
t11 = torch.tensor([4,5,6])
t12 = torch.hstack((t10,t11))   #1차원 텐서는 단순히 옆으로 이어붙인다.(dim=0 기준)
print(t12)
# >>> tensor([1,2,3,4,5,6])

t13 = torch.tensor([[1],[2],[3]])
t14 = torch.tensor([[4],[5],[6]])
t15 = torch.hstack((t13,t14))   #열 방향으로 합쳐진다.
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


# torch.vstack : 세로방향
# 1차원은 행으로 쌓임
# 2차원 이상은 첫 번째 차원(batch 차원) 기준으로 결합

# torch.hstack : 가로방향
# 1차원은 단순히 옆으로 이어붙임
# 2차원 이상은 두 번째 차원 기준으로 결합

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


## 숙제후기

처음 숙제를 하기전에 그래도 tensor에 대해 공부를 하고 적어서 공부를 하는게 낫지않을까? 라는 생각이 있어서 시작하기가 막막했는데 막상 그냥 시작해보니까 글로 읽을 때보다 훨씬 이해가 쉬웠습니다. 그리고 수업시간에 수업내용을 이해하기가 진짜 어려웠는데 이 숙제를 하면서 좀더 이해하기 수월해져서 정말 도움이 많이 되었습니다.